# Week 11 Assignment

### Your task is to choose one of the New York Times APIs, construct an interface in Python to read in the JSON data, and transform it into a pandas DataFrame.

##### I decided to use Best Sellers Lists Services from the Books API

In [31]:
# Below I imported the necessary modules

import json
import pandas as pd
import requests

# Below is my NYTimes API which lists the current top 15 best sellers and I read the data from the URL

url = f'https://api.nytimes.com/svc/books/v3/lists/current/hardcover-fiction.json?api-key=nS413b6etOqP6F6G9CXQFw5ANzHJDkVv'

r = requests.get(url)

# Below I specify where in the resulting .json file I am fetching data from

comment_list = json_data['results']['books']

# Below I specify which fields I am interested in and create a dataframe, along with moving over my index and printing the resulting dataframe

df = pd.DataFrame(comment_list, columns = ['rank',
                                               'primary_isbn10',
                                               'publisher',
                                               'title',
                                               'author',])

df = df.set_index('rank')

df

,primary_isbn10,publisher,title,author
rank,,,,
1,0385546025,Doubleday,THE JUDGE'S LIST,John Grisham
2,1984818503,Delacorte,BETTER OFF DEAD,Lee Child and Andrew Child
3,1538728621,Grand Central,THE WISH,Nicholas Sparks
4,0735222355,Viking,THE LINCOLN HIGHWAY,Amor Towles
5,198217367X,"Simon & Schuster, St. Martin's",STATE OF TERROR,Hillary Rodham Clinton and Louise Penny
6,1982168439,Scribner,CLOUD CUCKOO LAND,Anthony Doerr
7,1250220254,Holt,APPLES NEVER FALL,Liane Moriarty
8,1501171348,Simon & Schuster,THE LAST THING HE TOLD ME,Laura Dave
9,1982173610,Scribner,BILLY SUMMERS,Stephen King
10,0525559477,Viking,THE MIDNIGHT LIBRARY,Matt Haig
11,1982104414,Atria,FORGIVING PARIS,Karen Kingsbury
12,0593490592,Viking,SILVERVIEW,John Le Carré
13,1984818813,Ballantine,DEAR SANTA,Debbie Macomber
14,0812989430,Random House,OH WILLIAM!,Elizabeth Strout
15,0385545134,Doubleday,HARLEM SHUFFLE,Colson Whitehead